### ISSUE TITLE
Change all units to metric?

### ISSUE THREAD

**Issue by repparw** [ligi/SurvivalManual#156] opened 2020-12-11 18:12 UTC
I see units in different systems even in a single page (Ex. Basic medicine - Water, talks about liters, ounces and quarts) It would be easier/more helpful if all of them were in the same unit

**Comment by ligi** [comment] 2021-01-17 02:03
yes you are correct - should really do this - just closing this issue as duplicate of #44

**Closed** 2021-01-17 02:03 UTC
Labels: content
